// AUTO-GENERATED by scripts/build-scenes.mjs from content/manifest.json.
// Do not hand-edit — rerun the script instead, or edit the manifest.
import type { Scene } from "./types";

export const generatedScenes: Scene[] = [
  {
    "id": "scene-01-hook",
    "motion": "animate",
    "archetype": "Hook — Survival Resource",
    "durationInFrames": 150,
    "background": {
      "type": "image",
      "src": "images/scene-01-survival-seeds.jpg",
      "kenBurns": "zoom-in",
      "fit": "contain",
      "letterboxColor": "#0f2418"
    },
    "overlays": [
      {
        "type": "caption",
        "text": "Một nắm hạt nhỏ bé này từng là ranh giới giữa sự sống và cái chết giữa sa mạc.",
        "position": "top"
      }
    ],
    "transitionIn": {
      "type": "none"
    }
  },
  {
    "id": "scene-02-growth-chart",
    "motion": "static",
    "archetype": "Data Chart — Growth Comparison",
    "durationInFrames": 180,
    "background": {
      "type": "image",
      "src": "images/scene-02-growth-chart.jpg",
      "kenBurns": "none",
      "fit": "contain",
      "letterboxColor": "#F3EEE1"
    },
    "overlays": [
      {
        "type": "caption",
        "text": "Lúa nước cần tới 150 ngày để thu hoạch — trong khi giống lúa nhanh nhất chỉ mất 45 ngày."
      }
    ],
    "captionBar": {
      "color": "#F3EEE1",
      "heightPercent": 14,
      "position": "bottom"
    },
    "transitionIn": {
      "type": "fade"
    }
  },
  {
    "id": "scene-03-farming-migration",
    "motion": "static",
    "archetype": "E1/E6 — Farming + Migration",
    "durationInFrames": 180,
    "background": {
      "type": "image",
      "src": "images/scene-03-farming-migration.jpg",
      "kenBurns": "pan-right"
    },
    "overlays": [
      {
        "type": "caption",
        "text": "Người du mục vừa gieo hạt, vừa tiếp tục di chuyển không ngừng qua các thảo nguyên."
      }
    ],
    "transitionIn": {
      "type": "slide",
      "direction": "from-right"
    }
  },
  {
    "id": "scene-04-corridor-map",
    "motion": "static",
    "archetype": "Data Map — Migration Corridor",
    "durationInFrames": 210,
    "background": {
      "type": "image",
      "src": "images/scene-04-corridor-map.jpg",
      "kenBurns": "none",
      "fit": "contain",
      "letterboxColor": "#F5F2E0"
    },
    "overlays": [
      {
        "type": "caption",
        "text": "Từ Trung Á, hạt kê theo chân họ lan tới tận Lưỡng Hà — hàng ngàn cây số xa xôi."
      }
    ],
    "captionBar": {
      "color": "#F5F2E0",
      "heightPercent": 14,
      "position": "bottom"
    },
    "transitionIn": {
      "type": "wipe",
      "direction": "from-left"
    }
  },
  {
    "id": "scene-05-scale-value",
    "motion": "animate",
    "archetype": "Closing — Value Comparison",
    "durationInFrames": 150,
    "background": {
      "type": "image",
      "src": "images/scene-05-scale-value.jpg",
      "kenBurns": "zoom-out"
    },
    "overlays": [
      {
        "type": "caption",
        "text": "Với họ, một nắm hạt giống đôi khi còn quý hơn cả thanh kiếm."
      }
    ],
    "transitionIn": {
      "type": "fade"
    }
  }
];
